apiVersion: v1
kind: Service
metadata:
  name: notification-service
  labels:
    app: notification-service
    tier: backend
spec:
  type: ClusterIP
  ports:
  - port: 3004
    targetPort: 3004
    protocol: TCP
    name: http
  selector:
    app: notification-service
