apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    app: order-service
    tier: backend
spec:
  type: ClusterIP
  ports:
  - port: 3003
    targetPort: 3003
    protocol: TCP
    name: http
  selector:
    app: order-service
